[project]
name = "gamenet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lenny Ng'ang'a", email = "codewithlennylen254@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material>=9.7.7",
]

[project.scripts]
gamenet = "gamenet:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
